FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

ENV PYTHONPATH=/app/src

CMD ["flask", "run", "--host=0.0.0.0", "--app", "src.app", "--debug", "--reload"]
