version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: analytics
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    user: "472"  # Grafana runs as user 472 by default
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./csv-data:/usr/share/nginx/html/csv-data:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

  flask:
    build: ./preprocessing
    volumes:
      - ./preprocessing:/app
      - ./csv-data:/app/csv-data
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "5001:5001"
    depends_on:
      - postgres

volumes:
  postgres-data:
  grafana-data:
