apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: analytics
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      timescaledb: false
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      minInterval: 1m
