apiVersion: 1

datasources:
#  - name: Postgres
#    type: postgres
#    access: proxy
#    url: postgres:5432
#    database: analytics
#    user: admin
#    secureJsonData:
#      password: admin
#    jsonData:
#      sslmode: disable
#      postgresVersion: 1300
#      timescaledb: false
#      maxOpenConns: 100
#      maxIdleConns: 100
#      connMaxLifetime: 14400
#      minInterval: 1m

  - name: CSV
    type: yesoreyeram-infinity-datasource
    access: proxy
    jsonData:
      type: 'csv'
      url: 'http://nginx:80/csv-data'
